### ISSUE TITLE
Requested Changes

### ISSUE THREAD

**Issue by dfan** [jess2422/first-hack#1]
- Add link to participant Slack
- Add link to Devpost + short description of prizes
- For Hardware, add info on hardware lab (EQuad basement) and overview of the coolest gadgets we have
- For Machine Learning, add a link to the Kaggle titanic training exercise or another training one. Also add a link to Alexa skills
- Set a reminder for yourself to update dayof.hackprinceton.com to the new bebo link when it's ready (should be good by Tuesday)
- I think the favicon is the non-transparent background version (change it to the transparent one)
- Resources section not wrapping in mobile

**Comment by jess2422** [comment]
still waiting for ready day-of website, but link should be the same
